# ──────────────────────────────────────────────
# Profile: docker
# Carregado automaticamente quando a app sobe
# com -Dspring.profiles.active=docker
# ──────────────────────────────────────────────

# PostgreSQL
spring.datasource.url=jdbc:postgresql://postgres:5432/notification_db
spring.datasource.username=notification_user
spring.datasource.password=notification_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# RabbitMQ
spring.rabbitmq.host=order-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=ticket_rabbit
spring.rabbitmq.password=rabbit
